outdir: "/mnt/data/planter_outputs"
bbduk_parameters: "k=31 -Xmx5g"
rrna_db: "references/combined_rrna_ref.fasta"
trimmomatic_parameters: "ILLUMINACLIP:adapters.fasta:2:30:10 SLIDINGWINDOW:4:5 LEADING:5 TRAILING:5 MINLEN:25"
s3_bucket: "recombia.planter"
samples:
  - SRR12068547  # M. florum 
  - SRR8053131   # Piper methysticum
  - SRR29142729  # Gerbera hybrid cultivar
  # - SRR22420515  # Passiflora edulis; single end
  - SRR5936537   # Rhodiola rosea
  # - SRR2103848   # Photinus pyralis (firefly)
  - SRR28059386  # Gyrinops; agarwood, control-1
