version: '2'
services:
  pteryx:
    build: .
    image: planter
    stdin_open: True
    tty: True
    volumes:
      - ./pteryx/workflow:/planter/workflow
      - ./tests:/usr/src/planter/tests
      - ./tests/fixtures/mesoplasma:/planter/inputs
      - /mnt/data/planter_outputs:/planter/outputs
      - .:/usr/src/planter
