version: '2'
services:
  planter:
    build: .
    image: planter
    stdin_open: True
    tty: True
    environment:
      - TMPDIR=/mnt/data2/tmp
    volumes:
      - ./planter/workflow:/planter/workflow
      - ./tests:/usr/src/planter/tests
      - ./tests/fixtures/mesoplasma:/usr/src/planter/inputs
      - .:/usr/src/planter
      - /mnt/data:/mnt/data
      # - ./outputs:/usr/src/planter/outputs
      - /mnt/data2/planter_outputs:/usr/src/planter/outputs

