version: '2'
services:
  planter:
    build: .
    image: planter
    stdin_open: True
    tty: True
    environment:
      - TMPDIR=/mnt/data3/tmp
      - SNAKEMAKE_STORAGE_DIR=/mnt/data3/.snakemake_storage
    volumes:
      - ./planter/workflow:/planter/workflow
      - ./tests:/usr/src/planter/tests
      - ./tests/fixtures/mesoplasma:/usr/src/planter/inputs
      - .:/usr/src/planter
      - /mnt/data:/mnt/data
      # - ./outputs:/usr/src/planter/outputs
      - /mnt/data4/planter_outputs:/usr/src/planter/outputs
      #- /mnt/data2/planter_outputs:/usr/src/planter/outputs
      - /mnt/data3/tmp:/tmp
      - ~/.aws:/root/.aws
