name: Planter CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python 3.12
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'
        cache: 'pip'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip setuptools wheel
        python -m pip install -e .
        python -m pip install pytest pytest-cov black isort flake8 mypy
        # Ensure all required packages are installed
        python -m pip install pandas numpy biopython pyyaml flask
    
    - name: Run tests
      run: |
        make test
    
    - name: Generate coverage report
      run: |
        make coverage
        pytest --cov=planter --cov-report=xml tests/ -k "not slow"
    
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        file: ./coverage.xml
        fail_ci_if_error: false

  lint:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python 3.12
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'
        cache: 'pip'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip setuptools wheel
        python -m pip install -e .
        python -m pip install pytest pytest-cov black isort flake8 mypy
        # Ensure all required packages are installed
        python -m pip install pandas numpy biopython pyyaml flask
    
    - name: Run code quality checks
      run: |
        make check
        make lint

  slow-tests:
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python 3.12
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'
        cache: 'pip'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip setuptools wheel
        python -m pip install -e .
        python -m pip install pytest pytest-cov black isort flake8 mypy
        # Ensure all required packages are installed
        python -m pip install pandas numpy biopython pyyaml flask
    
    - name: Run slow tests
      run: |
        make test-slow

  build-image:
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    needs: [test, lint]
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    
    - name: Build Docker image
      run: |
        make image